import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: 'Stimme',
  navDocs: 'Docs',
  navBlog: 'Blog',
  switcherLabel: 'Sprache wechseln',
  bannerText: 'Diese Seite ist auf Deutsch verfügbar.',
  bannerView: 'Ansehen',
  bannerDismiss: 'Schließen',
  subOverview: 'Überblick',
  subUseCases: 'Anwendungsfälle',
  subAlternatives: 'Alternativen',
  subDownload: 'Download',
  subChangelog: 'Neuigkeiten',
  subTalk: 'Kontakt',
  dlMac: 'Für Mac herunterladen',
  dlLinux: 'Für Linux herunterladen',
  dlWindows: 'Für Windows herunterladen',
  dlWindowsX64: 'Windows auf Intel oder AMD',
  dlWindowsArm64: 'Windows auf ARM',
  dlOther: 'Andere Plattformen',
  dlArchMac: 'Macs mit Apple Chip (M1 oder neuer)',
  dlArchLinux: 'Debian & Ubuntu (.deb, 64-Bit)',
  dlArchWindowsX64: 'Windows 10 & 11, 64-Bit',
  dlArchWindowsArm64: 'Windows 11 auf Snapdragon oder Surface',
  dlEarly: 'Früh',
  dlWindowsUnsigned:
    'Die Windows-Builds sind noch nicht signiert, deshalb warnt Windows beim ersten Start.',
  dlWindowsUnsignedLink: 'So kommen Sie daran vorbei',
  talkHeading: 'Kontakt',
  talkBody:
    'Fragen, Feedback oder ein Gerät, das Sie sich von uns wünschen? Am besten erreichen Sie uns per E-Mail — wir lesen jede Nachricht und antworten, so schnell wir können.',
  talkButton: 'Schreiben Sie uns',
  talkWritePre: 'Oder schreiben Sie direkt an ',
  talkWritePost: '.',
  footerEmail: 'Schreiben Sie uns',
  footerAbout: 'Über uns',
  footerPrivacy: 'Datenschutz',
  footerPrompts: 'Sprachgenerator',
  footerPlatform: 'Plattform',
  footerMore: 'Mehr',
  footerTools: 'Tools',
  notFoundTitle: "Seite nicht gefunden",
  notFoundBody: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
  notFoundHome: "Zur Startseite",
  footerSource: 'Quellcode auf GitHub ansehen',
  postBack: '← Zurück zum Blog',
  postUpdated: 'aktualisiert',
};
