import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: 'Stimme',
  navDocs: 'Docs',
  navBlog: 'Blog',
  switcherLabel: 'Sprache wechseln',
  bannerText: 'Diese Seite ist auf Deutsch verfügbar.',
  bannerView: 'Ansehen',
  bannerDismiss: 'Schließen',
  subOverview: 'Überblick',
  subUseCases: 'Anwendungsfälle',
  subAlternatives: 'Alternativen',
  subDownload: 'Download',
  subChangelog: 'Neuigkeiten',
  subTalk: 'Kontakt',
  dlMac: 'Für Mac herunterladen',
  dlLinux: 'Für Linux herunterladen',
  dlOther: 'andere Plattformen',
  talkHeading: 'Kontakt',
  talkBody:
    'Fragen, Feedback oder ein Gerät, das Sie sich von uns wünschen? Am besten erreichen Sie uns per E-Mail — wir lesen jede Nachricht und antworten, so schnell wir können.',
  talkButton: 'Schreiben Sie uns',
  talkWritePre: 'Oder schreiben Sie direkt an ',
  talkWritePost: '.',
  footerEmail: 'Schreiben Sie uns',
  footerAbout: 'Über uns',
  footerPrompts: 'Sprachgenerator',
  footerMore: 'Mehr',
  notFoundTitle: "Seite nicht gefunden",
  notFoundBody: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
  notFoundHome: "Zur Startseite",
  footerSource: 'Quellcode auf GitHub ansehen',
  postBack: '← zurück zum Blog',
  postUpdated: 'aktualisiert',
};
