import type { UIStrings } from '../i18n';

/**
 * The default locale, and the fallback every other locale falls back to
 * (`t()` returns this when a code has no entry). Nothing here may be
 * missing: a key absent from this file is absent everywhere.
 */
export const ui: UIStrings = {
  navVoice: 'Voice',
  navDocs: 'Docs',
  navBlog: 'Blog',
  switcherLabel: 'Change language',
  bannerText: 'This page is available in English.',
  bannerView: 'View',
  bannerDismiss: 'Dismiss',
  subOverview: 'Overview',
  subUseCases: 'Use Cases',
  subAlternatives: 'Alternatives',
  subDownload: 'Download',
  subChangelog: "What's New",
  subTalk: 'Talk to Us',
  dlMac: 'Download for Mac',
  dlMacAppStore: 'Download on the Mac App Store',
  dlLinux: 'Download for Linux',
  dlLinuxArm64: 'Download for Linux on ARM',
  dlMsStore: 'Get it from Microsoft Store',
  dlSnapStore: 'Get it from the Snap Store',
  dlWindows: 'Download for Windows',
  dlWindowsArm64: 'Download for Windows on ARM',
  dlOther: 'Other Platforms',
  dlArchMac: 'Macs with Apple chip (M1 or newer)',
  dlArchMacAppStore: 'macOS 12 or later, Apple chip',
  dlArchLinux: 'Debian & Ubuntu (.deb, Intel & AMD 64-bit)',
  dlArchLinuxArm64: 'Debian & Ubuntu (.deb, ARM64)',
  dlArchMsStore: 'Windows 10 & 11, Intel, AMD & ARM',
  dlArchSnapStore: 'Ubuntu & most Linux distros (Intel, AMD & ARM)',
  dlSnapInstall: 'Or from a terminal:',
  dlArchWindowsX64: 'Windows 10 & 11, Intel & AMD (x64)',
  dlArchWindowsArm64: 'Windows 11, Snapdragon (ARM64)',
  dlWindowsUnsigned:
  "The direct Windows downloads aren't code-signed, so Windows warns on first launch. The Microsoft Store version is signed.",
  dlWindowsUnsignedLink: 'How to get past it',
  dlAllDownloads: 'All downloads and installers',
  dlLatestRelease: 'Latest WaveKat Voice release',
  talkHeading: 'Talk to us',
  talkBody:
  'Questions, feedback, or a device you wish we supported? Email is the best way to reach us — we read every message and reply as soon as we can.',
  talkButton: 'Email us',
  talkWritePre: 'Or write to ',
  talkWritePost: ' directly.',
  footerEmail: 'Email us',
  footerSource: 'View source on GitHub',
  footerAbout: 'About',
  footerPrivacy: 'Privacy',
  footerPrompts: 'Prompt Generator',
  footerPlatform: 'Platform',
  footerMore: 'More',
  footerTools: 'Tools',
  notFoundTitle: "Page not found",
  notFoundBody: "The page you're looking for doesn't exist or has moved.",
  notFoundHome: "Go to the homepage",
  postBack: '← Back to Blog',
  postUpdated: 'updated',
};
