import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: 'Voix',
  navDocs: 'Docs',
  navBlog: 'Blog',
  switcherLabel: 'Changer de langue',
  bannerText: 'Cette page est disponible en français.',
  bannerView: 'Voir',
  bannerDismiss: 'Fermer',
  subOverview: 'Aperçu',
  subUseCases: "Cas d'usage",
  subAlternatives: 'Alternatives',
  subDownload: 'Télécharger',
  subChangelog: 'Nouveautés',
  subTalk: 'Nous contacter',
  dlMac: 'Télécharger pour Mac',
  dlLinux: 'Télécharger pour Linux',
  dlWindows: 'Télécharger pour Windows',
  dlWindowsArm64: 'Télécharger pour Windows sur ARM',
  dlOther: 'Autres plateformes',
  dlArchMac: 'Mac avec puce Apple (M1 ou plus récent)',
  dlArchLinux: 'Debian et Ubuntu (.deb, 64 bits)',
  dlArchWindowsX64: 'Windows 10 et 11, Intel et AMD (x64)',
  dlArchWindowsArm64: 'Windows 11, Snapdragon (ARM64)',
  dlEarly: 'Débuts',
  dlWindowsUnsigned:
    "Les versions Windows ne sont pas encore signées : Windows affiche un avertissement au premier lancement.",
  dlWindowsUnsignedLink: 'Comment passer outre',
  talkHeading: 'Nous contacter',
  talkBody:
    'Une question, un retour, ou un appareil que vous aimeriez nous voir prendre en charge ? L’e-mail est le meilleur moyen de nous joindre — nous lisons chaque message et répondons dès que possible.',
  talkButton: 'Écrivez-nous',
  talkWritePre: 'Ou écrivez directement à ',
  talkWritePost: '.',
  footerEmail: 'Écrivez-nous',
  footerAbout: 'À propos',
  footerPrivacy: 'Confidentialité',
  footerPrompts: 'Générateur vocal',
  footerPlatform: 'Plateforme',
  footerMore: 'Plus',
  footerTools: 'Outils',
  notFoundTitle: "Page introuvable",
  notFoundBody: "La page que vous cherchez n'existe pas ou a été déplacée.",
  notFoundHome: "Aller à l'accueil",
  footerSource: 'Voir le code source sur GitHub',
  postBack: '← Retour au blog',
  postUpdated: 'mis à jour le',
};
