import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: 'Voce',
  navDocs: 'Documentazione',
  navBlog: 'Blog',
  switcherLabel: 'Cambia lingua',
  bannerText: 'Questa pagina è disponibile in italiano.',
  bannerView: 'Visualizza',
  bannerDismiss: 'Chiudi',
  subOverview: 'Panoramica',
  subUseCases: 'Casi d’uso',
  subAlternatives: 'Alternative',
  subDownload: 'Download',
  subChangelog: 'Novità',
  subTalk: 'Contattaci',
  dlMac: 'Scarica per Mac',
  dlMacAppStore: 'Scarica su Mac App Store',
  dlLinux: 'Scarica per Linux',
  dlLinuxArm64: 'Scarica per Linux su ARM',
  dlMsStore: 'Scarica da Microsoft Store',
  dlWindows: 'Scarica per Windows',
  dlWindowsArm64: 'Scarica per Windows su ARM',
  dlOther: 'Altre piattaforme',
  dlArchMac: 'Mac con chip Apple (M1 o successivo)',
  dlArchMacAppStore: 'macOS 12 o successivo, chip Apple',
  dlArchLinux: 'Debian e Ubuntu (.deb, 64 bit)',
  dlArchLinuxArm64: 'Debian e Ubuntu (.deb, ARM64)',
  dlArchMsStore: 'Windows 10 e 11, Intel, AMD e ARM',
  dlArchWindowsX64: 'Windows 10 e 11, Intel e AMD (x64)',
  dlArchWindowsArm64: 'Windows 11, Snapdragon (ARM64)',
  dlEarly: 'Iniziale',
  dlWindowsUnsigned:
    'I download diretti per Windows non sono firmati, quindi Windows avvisa al primo avvio. La versione di Microsoft Store è firmata.',
  dlWindowsUnsignedLink: 'Come procedere',
  dlAllDownloads: 'Tutti i download e gli installer',
  talkHeading: 'Contattaci',
  talkBody:
    'Domande, suggerimenti o un dispositivo che vorresti vedere supportato? L’email è il modo migliore per raggiungerci: leggiamo ogni messaggio e rispondiamo il prima possibile.',
  talkButton: 'Scrivici un’email',
  talkWritePre: 'Oppure scrivi direttamente a ',
  talkWritePost: '.',
  footerEmail: 'Scrivici un’email',
  footerAbout: 'Chi siamo',
  footerPrivacy: 'Privacy',
  footerPrompts: 'Generatore vocale',
  footerPlatform: 'Piattaforma',
  footerMore: 'Altro',
  footerTools: 'Strumenti',
  notFoundTitle: "Pagina non trovata",
  notFoundBody: "La pagina che cerchi non esiste o è stata spostata.",
  notFoundHome: "Vai alla home",
  footerSource: 'Vedi il codice sorgente su GitHub',
  postBack: '← Torna al blog',
  postUpdated: 'aggiornato',
};
