import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: 'Voce',
  navDocs: 'Documentazione',
  navBlog: 'Blog',
  switcherLabel: 'Cambia lingua',
  bannerText: 'Questa pagina è disponibile in italiano.',
  bannerView: 'Visualizza',
  bannerDismiss: 'Chiudi',
  subOverview: 'Panoramica',
  subUseCases: 'Casi d’uso',
  subAlternatives: 'Alternative',
  subDownload: 'Download',
  subChangelog: 'Novità',
  subTalk: 'Contattaci',
  dlMac: 'Scarica per Mac',
  dlLinux: 'Scarica per Linux',
  dlWindows: 'Scarica per Windows',
  dlWindowsX64: 'Windows su Intel o AMD',
  dlWindowsArm64: 'Windows su ARM',
  dlOther: 'Altre piattaforme',
  dlArchMac: 'Mac con chip Apple (M1 o successivo)',
  dlArchLinux: 'Debian e Ubuntu (.deb, 64 bit)',
  dlArchWindowsX64: 'Windows 10 e 11, 64 bit',
  dlArchWindowsArm64: 'Windows 11 su Snapdragon o Surface',
  dlEarly: 'Iniziale',
  dlWindowsUnsigned:
    'Le versioni per Windows non sono ancora firmate, quindi Windows avvisa al primo avvio.',
  dlWindowsUnsignedLink: 'Come procedere',
  talkHeading: 'Contattaci',
  talkBody:
    'Domande, suggerimenti o un dispositivo che vorresti vedere supportato? L’email è il modo migliore per raggiungerci: leggiamo ogni messaggio e rispondiamo il prima possibile.',
  talkButton: 'Scrivici un’email',
  talkWritePre: 'Oppure scrivi direttamente a ',
  talkWritePost: '.',
  footerEmail: 'Scrivici un’email',
  footerAbout: 'Chi siamo',
  footerPrivacy: 'Privacy',
  footerPrompts: 'Generatore vocale',
  footerPlatform: 'Piattaforma',
  footerMore: 'Altro',
  footerTools: 'Strumenti',
  notFoundTitle: "Pagina non trovata",
  notFoundBody: "La pagina che cerchi non esiste o è stata spostata.",
  notFoundHome: "Vai alla home",
  footerSource: 'Vedi il codice sorgente su GitHub',
  postBack: '← Torna al blog',
  postUpdated: 'aggiornato',
};
