import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: '音声',
  navDocs: 'ドキュメント',
  navBlog: 'ブログ',
  switcherLabel: '言語を切り替える',
  bannerText: 'このページは日本語でご覧いただけます。',
  bannerView: '表示',
  bannerDismiss: '閉じる',
  subOverview: '概要',
  subUseCases: '活用例',
  subAlternatives: '代替ツール',
  subDownload: 'ダウンロード',
  subChangelog: '更新情報',
  subTalk: 'お問い合わせ',
  dlMac: 'Mac 版をダウンロード',
  dlMacAppStore: 'Mac App Store からダウンロード',
  dlLinux: 'Linux 版をダウンロード',
  dlLinuxArm64: 'ARM 版 Linux をダウンロード',
  dlMsStore: 'Microsoft Store から入手',
  dlWindows: 'Windows 版をダウンロード',
  dlWindowsArm64: 'ARM 版 Windows をダウンロード',
  dlOther: 'その他のプラットフォーム',
  dlArchMac: 'Apple シリコン搭載 Mac（M1 以降）',
  dlArchMacAppStore: 'macOS 12 以降、Apple シリコン',
  dlArchLinux: 'Debian・Ubuntu（.deb、64ビット）',
  dlArchLinuxArm64: 'Debian・Ubuntu（.deb、ARM64）',
  dlArchMsStore: 'Windows 10・11（Intel・AMD・ARM）',
  dlArchWindowsX64: 'Windows 10・11（Intel・AMD、x64）',
  dlArchWindowsArm64: 'Windows 11（Snapdragon、ARM64）',
  dlEarly: '早期版',
  dlWindowsUnsigned:
    '直接ダウンロードした Windows 版はコード署名されていないため、初回起動時に警告が表示されます。Microsoft Store 版は署名済みです。',
  dlWindowsUnsignedLink: '進める方法',
  dlWindowsDirect: 'Windows 版の直接ダウンロード（.exe）',

  talkHeading: 'お問い合わせ',
  talkBody:
    'ご質問やご意見、対応してほしいデバイスはありますか？メールが一番確実な連絡方法です。いただいたメッセージはすべて読み、できる限り早くお返事します。',
  talkButton: 'メールを送る',
  talkWritePre: 'または ',
  talkWritePost: ' まで直接ご連絡ください。',
  footerEmail: 'メールを送る',
  footerAbout: 'WaveKat について',
  footerPrivacy: 'プライバシー',
  footerPrompts: '音声ジェネレーター',
  footerPlatform: 'プラットフォーム',
  footerMore: 'その他',
  footerTools: 'ツール',
  notFoundTitle: "ページが見つかりません",
  notFoundBody: "お探しのページは存在しないか、移動しました。",
  notFoundHome: "ホームへ戻る",
  footerSource: 'GitHub でソースを見る',
  postBack: '← ブログに戻る',
  postUpdated: '更新日',
};
