import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: '語音',
  navDocs: '文件',
  navBlog: '部落格',
  switcherLabel: '切換語言',
  bannerText: '本頁面有繁體中文版本。',
  bannerView: '查看',
  bannerDismiss: '關閉',
  subOverview: '概覽',
  subUseCases: '應用情境',
  subAlternatives: '替代方案',
  subDownload: '下載',
  subChangelog: '更新內容',
  subTalk: '聯絡我們',
  dlMac: '下載 Mac 版',
  dlMacAppStore: '從 Mac App Store 下載',
  dlLinux: '下載 Linux 版',
  dlLinuxArm64: '下載 ARM 版 Linux',
  dlMsStore: '從 Microsoft Store 取得',
  dlWindows: '下載 Windows 版',
  dlWindowsArm64: '下載 ARM 版 Windows',
  dlOther: '其他平台',
  dlArchMac: '搭載 Apple 晶片的 Mac（M1 或更新機型）',
  dlArchMacAppStore: 'macOS 12 或更新版本，Apple 晶片',
  dlArchLinux: 'Debian 與 Ubuntu（.deb，64 位元）',
  dlArchLinuxArm64: 'Debian 與 Ubuntu（.deb，ARM64）',
  dlArchMsStore: 'Windows 10 與 11，Intel、AMD 與 ARM',
  dlArchWindowsX64: 'Windows 10 與 11，Intel 與 AMD（x64）',
  dlArchWindowsArm64: 'Windows 11，Snapdragon（ARM64）',
  dlEarly: '早期版本',
  dlWindowsUnsigned:
    '直接下載的 Windows 版尚未進行程式碼簽章，首次啟動時系統會跳出提醒；Microsoft Store 版本已簽章。',
  dlWindowsUnsignedLink: '如何繼續安裝',
  dlAllDownloads: '所有下載與安裝程式',
  dlLatestRelease: 'WaveKat Voice 最新版本',
  talkHeading: '聯絡我們',
  talkBody:
    '有疑問、建議，或希望我們支援某款裝置？電子郵件是聯絡我們的最佳方式——我們會閱讀每一則訊息，並盡快回覆。',
  talkButton: '寄信給我們',
  talkWritePre: '或直接寫信至 ',
  talkWritePost: '。',
  footerEmail: '寄信給我們',
  footerAbout: '關於',
  footerPrivacy: '隱私權政策',
  footerPrompts: '語音產生器',
  footerPlatform: '平台',
  footerMore: '更多',
  footerTools: '工具',
  notFoundTitle: "找不到頁面",
  notFoundBody: "您要找的頁面不存在或已被移動。",
  notFoundHome: "返回首頁",
  footerSource: '在 GitHub 上查看原始碼',
  postBack: '← 返回部落格',
  postUpdated: '更新於',
};
