import type { UIStrings } from '../i18n';

export const ui: UIStrings = {
  navVoice: '语音',
  navDocs: '文档',
  navBlog: '博客',
  switcherLabel: '切换语言',
  bannerText: '本页面有简体中文版本。',
  bannerView: '查看',
  bannerDismiss: '关闭',
  subOverview: '概览',
  subUseCases: '应用场景',
  subAlternatives: '替代方案',
  subDownload: '下载',
  subChangelog: '更新日志',
  subTalk: '联系我们',
  dlMac: '下载 Mac 版',
  dlMacAppStore: '从 Mac App Store 下载',
  dlLinux: '下载 Linux 版',
  dlLinuxArm64: '下载 ARM 版 Linux',
  dlMsStore: '从 Microsoft Store 获取',
  dlSnapStore: '从 Snap Store 获取',
  dlWindows: '下载 Windows 版',
  dlWindowsArm64: '下载 ARM 版 Windows',
  dlOther: '其他平台',
  dlArchMac: '搭载 Apple 芯片的 Mac（M1 或更新机型）',
  dlArchMacAppStore: 'macOS 12 或更高版本，Apple 芯片',
  dlArchLinux: 'Debian 与 Ubuntu（.deb，Intel 与 AMD 64 位）',
  dlArchLinuxArm64: 'Debian 与 Ubuntu（.deb，ARM64）',
  dlArchMsStore: 'Windows 10 与 11，Intel、AMD 与 ARM',
  dlArchSnapStore: 'Ubuntu 与大多数 Linux 发行版（Intel、AMD 与 ARM）',
  dlSnapInstall: '或在终端中运行：',
  dlArchWindowsX64: 'Windows 10 与 11，Intel 与 AMD（x64）',
  dlArchWindowsArm64: 'Windows 11，骁龙（ARM64）',
  dlWindowsUnsigned:
  '直接下载的 Windows 版尚未进行代码签名，首次启动时系统会弹出提醒；Microsoft Store 版本已签名。',
  dlWindowsUnsignedLink: '如何继续安装',
  dlAllDownloads: '所有下载与安装程序',
  dlLatestRelease: 'WaveKat Voice 最新版本',
  talkHeading: '联系我们',
  talkBody:
  '有疑问、建议，或希望我们支持某种设备？邮件是联系我们的最佳方式——我们会阅读每一条消息，并尽快回复。',
  talkButton: '给我们发邮件',
  talkWritePre: '或直接写信至 ',
  talkWritePost: '。',
  footerEmail: '给我们发邮件',
  footerSource: '在 GitHub 上查看源码',
  footerAbout: '关于',
  footerPrivacy: '隐私政策',
  footerPrompts: '语音生成器',
  footerPlatform: '平台',
  footerMore: '更多',
  footerTools: '工具',
  notFoundTitle: "页面不存在",
  notFoundBody: "您要找的页面不存在或已被移动。",
  notFoundHome: "返回首页",
  postBack: '← 返回博客',
  postUpdated: '更新于',
};
